In [160]:
import pandas
import numpy as np
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import matplotlib.image as pltimg
import pydotplus 
from IPython.display import Image
from sklearn import metrics
import graphviz 
from sklearn.metrics import confusion_matrix
import pickle

In [68]:
df=pandas.read_csv("column_3C.dat",sep=' ',header=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 7 columns):
63.03    309 non-null float64
22.55    309 non-null float64
39.61    309 non-null float64
40.48    309 non-null float64
98.67    309 non-null float64
-0.25    309 non-null float64
DH       309 non-null object
dtypes: float64(6), object(1)
memory usage: 17.0+ KB


In [69]:
df.columns=['pelvic_incidence','pelvic_tilt','lumbar_lordosis_angle','sacral_slope','pelvic_radius','degree_spondylolisthesis','class']

In [70]:
df=df.sample(frac=1)
print(df)

     pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
116             86.04        38.75                  47.87         47.29   
13              57.30        24.19                  47.00         33.11   
23              36.13        22.76                  29.00         13.37   
40              46.44         8.40                  29.04         38.05   
247             47.32         8.57                  35.56         38.75   
..                ...          ...                    ...           ...   
268             37.14        16.48                  24.00         20.66   
0               39.06        10.06                  25.02         29.00   
211             44.36         8.95                  46.90         35.42   
169             64.81        15.17                  58.84         49.64   
293             46.24        10.06                  37.00         36.17   

     pelvic_radius  degree_spondylolisthesis class  
116         122.09                     61.99  

In [283]:
testSet,evaluateSet=np.split(df,[int(.4*len(df.index))])
print(testSet)
print(evaluateSet)

     pelvic_incidence  pelvic_tilt  lumbar_lordosis_angle  sacral_slope  \
116             86.04        38.75                  47.87         47.29   
13              57.30        24.19                  47.00         33.11   
23              36.13        22.76                  29.00         13.37   
40              46.44         8.40                  29.04         38.05   
247             47.32         8.57                  35.56         38.75   
..                ...          ...                    ...           ...   
144             85.64        42.69                  78.75         42.95   
273             43.19         9.98                  28.94         33.22   
210             54.92        18.97                  51.60         35.95   
295             39.66        16.21                  36.67         23.45   
200             67.51        33.28                  96.28         34.24   

     pelvic_radius  degree_spondylolisthesis class  
116         122.09                     61.99  

In [284]:
feature_cols = ['pelvic_incidence','pelvic_tilt','lumbar_lordosis_angle','sacral_slope','pelvic_radius','degree_spondylolisthesis']
X = testSet[feature_cols] # Features
y = testSet['class']#class
#evaluateSet=evaluateSet[evaluateSet['class'] != 'SL']
#evaluateSet=evaluateSet[evaluateSet['degree_spondylolisthesis'] <= 21.445]
#evaluateSet=evaluateSet[evaluateSet['pelvic_radius'] > 119.505]
#evaluateSet=evaluateSet[evaluateSet['sacral_slope'] > 28.45]
Xp=evaluateSet[feature_cols]# preFeatures
yp=evaluateSet['class']# preClass

In [285]:
clf = DecisionTreeClassifier(max_depth=3,criterion='entropy',min_samples_leaf=10)#tree control
clf = clf.fit(X,y)
y_pred = clf.predict(Xp)
print("Accuracy:",metrics.accuracy_score(yp, y_pred))
dot_data = tree.export_graphviz(clf, out_file=None, 
                      feature_names=feature_cols,  
                      class_names=clf.classes_,  
                      filled=True, rounded=True,  
                      special_characters=True)  
graph = graphviz.Source(dot_data)
graph.render()



Accuracy: 0.8333333333333334


'Source.gv.pdf'

In [286]:
print(clf.classes_)
print(confusion_matrix(yp,y_pred))

['DH' 'NO' 'SL']
[[22  9  0]
 [12 40  2]
 [ 1  7 93]]


In [287]:
print(clf.tree_.value)

[[[28. 46. 49.]]

 [[28. 46.  2.]]

 [[19. 11.  2.]]

 [[17.  5.  0.]]

 [[ 2.  6.  2.]]

 [[ 9. 35.  0.]]

 [[ 7.  5.  0.]]

 [[ 2. 30.  0.]]

 [[ 0.  0. 47.]]]


In [288]:
np.set_printoptions(threshold=np.inf)
temp=clf.decision_path(Xp).todense()
print(Xp['pelvic_radius'])
print(yp)
print(temp)

158     95.25
138    109.06
35     132.26
267    113.81
60     129.96
        ...  
268    125.01
0      114.41
211    129.22
169    111.68
293    128.06
Name: pelvic_radius, Length: 186, dtype: float64
158    SL
138    SL
35     DH
267    NO
60     SL
       ..
268    NO
0      DH
211    NO
169    SL
293    NO
Name: class, Length: 186, dtype: object
[[1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 1 1 0 0]
 [1 1 1 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0